### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gmag11** [davidnemec/bitwarden-to-keepass#11]
Hello,

I'm trying to setup your script. Thank you!

I've tried to run it with venv and docker with same result in both cases. Just after it creates keepass database script chashes with a "list index out of range" error:

```
python3 bitwarden-to-keepass.py --bw-session $BW_SESSION --database-path '$DATABASE_PATH' --database-password '$DATABASE_PASSWORD' --bw-path $BW_PATH
Traceback (most recent call last):
  File "src/lxml/builder.py", line 175, in lxml.builder.ElementMaker.__init__.add_text
  File "src/lxml/etree.pyx", line 1176, in lxml.etree._Element.__getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmartin/bitwarden2keepass/bitwarden-to-keepass.py", line 179, in <module>
    check_args(args) and bitwarden_to_keepass(args)
  File "/home/gmartin/bitwarden2keepass/bitwarden-to-keepass.py", line 39, in bitwarden_to_keepass
    groups_by_id = load_folders(folders)
  File "/home/gmartin/bitwarden2keepass/bitwarden-to-keepass.py", line 127, in load_folders
    FolderType.bfs_traverse_execute(folder_root, add_keepass_group)
  File "/home/gmartin/bitwarden2keepass/folder.py", line 59, in bfs_traverse_execute
    callback(child)
  File "/home/gmartin/bitwarden2keepass/bitwarden-to-keepass.py", line 123, in add_keepass_group
    new_group: KPGroup = kp.add_group(parent_group, folder.name)
  File "/home/gmartin/bitwarden2keepass/.venv/lib/python3.9/site-packages/pykeepass/pykeepass.py", line 435, in add_group
    group = Group(name=group_name, notes=notes, kp=self)
  File "/home/gmartin/bitwarden2keepass/.venv/lib/python3.9/site-packages/pykeepass/group.py", line 30, in __init__
    self._element.append(E.Name(name))
  File "src/lxml/builder.py", line 228, in lxml.builder.ElementMaker.__call__
  File "src/lxml/builder.py", line 177, in lxml.builder.ElementMaker.__init__.add_text
  File "src/lxml/etree.pyx", line 1039, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```
I've tried this with two different accounts. First with hundreds of entries and another with only a few.

Let me know if you need more data.

**Comment by davidnemec** [comment]
Hello,
your issue seems to be folder/structure related. Do you use something special in your folder names?

**Comment by gmag11** [comment]
Repository is cloned in `/home/gmartin/bitwarden2keepass`

`.env` file contains this line:
```
DATABASE_PATH=/home/gmartin/bitwarden2keepass/bitwarden-export.kdbx
```
When running as venv I run `source .env` before calling Python script with `python3 bitwarden-to-keepass.py --bw-session $BW_SESSION --database-path '$DATABASE_PATH' --database-password '$DATABASE_PASSWORD' --bw-path $BW_PATH`

**Comment by gmag11** [comment]
Finally I discovered what happened. I had some entries in Bitwarden with non ascii codes, probably caused by export process in my former password manager. Now it runs fine.
