### ISSUE TITLE
Export Fails

### ISSUE THREAD

**Issue by thejockel** [davidnemec/bitwarden-to-keepass#15]
Hey :)
unfortunately the export fails :(
Does anyone has an similar issue?

Server: OnPremise
Server Installed: 2023.10.3
Web Installed: 2023.10.2

Exporter Client:
OS: Debian 11
Docker: 24.0.7

```
source .env
```

```
$BW_PATH config server $BW_Server
Could not find dir, "/root/.config/Bitwarden CLI"; creating it instead.
Could not find data file, "/root/.config/Bitwarden CLI/data.json"; creating it instead.
Saved setting `config`.
```

```
$BW_PATH login --apikey
You are logged in!

To unlock your vault, use the `unlock` command. ex:
$ bw unlock
```

```
export BW_SESSION=`$BW_PATH unlock $BW_Password --raw`
```

```
bw login --check
You are logged in!
```

```
python3 bitwarden-to-keepass.py
2023-12-11 07:10:13 :: INFO :: KeePass database does not exist, creating a new one.
2023-12-11 07:10:16 :: INFO :: Folders done (1).
/usr/local/lib/node_modules/@bitwarden/cli/node_modules/proper-lockfile/lib/lockfile.js:68
                return callback(Object.assign(new Error('Lock file is already being held'), { code: 'ELOCKED', file }));
                                              ^

Error: Lock file is already being held
    at /usr/local/lib/node_modules/@bitwarden/cli/node_modules/proper-lockfile/lib/lockfile.js:68:47
    at callback (/usr/local/lib/node_modules/@bitwarden/cli/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:208:5) {
  code: 'ELOCKED',
  file: '/root/.config/Bitwarden CLI/data.json'
}

Node.js v18.13.0
Traceback (most recent call last):
  File "/bitwarden-to-keepass/bitwarden-to-keepass.py", line 211, in <module>
    check_args(args) and bitwarden_to_keepass(args)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bitwarden-to-keepass/bitwarden-to-keepass.py", line 42, in bitwarden_to_keepass
    items = subprocess.check_output([args.bw_path, 'list', 'items', '--session', args.bw_session], encoding='utf8')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/bw', 'list', 'items', '--session', 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]' returned non-zero exit status 1.
```

Thanks in advance
Jockel

**Comment by thejockel** [comment]
Problem solved itself :man_shrugging: 

THX Jockel
