### ISSUE TITLE
bad argument type: NoneType(None)

### ISSUE THREAD

**Issue by basbebe** [davidnemec/bitwarden-to-keepass#2]
unfortunately, the script crashes when I try to run it.
I used `docker-compose run bitwarden-to-keepass`.

After I enter my credentials, I get two infos:

```console
INFO:root:Folders done (X).
INFO:root:Starting to process XXXX items.
```

Then a few warnings (all the same):
```console
…
WARNING:root:Skipping credit card item "ZZZZZZZ".
WARNING:root:Skipping credit card item "YYYYYYY".
…
```

directly after these, this:

```console
Traceback (most recent call last):
  File "/bitwarden-to-keepass/bitwarden-to-keepass.py", line 137, in <module>
    check_args(args) and bitwarden_to_keepass(args)
  File "/bitwarden-to-keepass/bitwarden-to-keepass.py", line 72, in bitwarden_to_keepass
    entry.set_custom_property(str(field['name']), field['value'])
  File "/usr/local/lib/python3.9/site-packages/pykeepass/entry.py", line 256, in set_custom_property
    return self._set_string_field(key, value)
  File "/usr/local/lib/python3.9/site-packages/pykeepass/entry.py", line 88, in _set_string_field
    self._element.append(E.String(E.Key(key), E.Value(value)))
  File "src/lxml/builder.py", line 226, in lxml.builder.ElementMaker.__call__
TypeError: bad argument type: NoneType(None)
```

**Comment by basbebe** [comment]
using the script without docker, I get the same result.

**Comment by davidnemec** [comment]
Thanks for reporting. Looks like you have some custom fields with empty value which is returned as `null` from the api.

Could you try running export again from this branch to confirm? `git clone -b custom-fields-always-force-string git@github.com:davidnemec/bitwarden-to-keepass.git`

**Comment by basbebe** [comment]
```console
git checkout origin/custom-fields-always-force-string
```
removed the ould image and re-ran `docker-compose`.

Worked perfectly, thank you very much!

**Comment by basbebe** [comment]
love this tool, thank you so much!
