### ISSUE TITLE
i have problem when  i try to run it:

### ISSUE THREAD

**Issue by yoge67855** [davidnemec/bitwarden-to-keepass#4]
Traceback (most recent call last):
  File "/usr/bin/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/bin/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/bin/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/bin/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/bin/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/bin/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/bin/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/bin/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/bin/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/bin/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/bin/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/bin/compose/cli/main.py", line 80, in main
    command_func()
  File "/usr/bin/compose/cli/main.py", line 189, in perform_command
    project = project_from_options('.', options)
  File "/usr/bin/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/bin/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/bin/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/bin/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/home/xyz/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by davidnemec** [comment]
Looks like your docker service is not running. This error has nothing to do with code in this repository.

**Comment by yoge67855** [comment]
@davidnemec should i run "systemctl enable --now docker.service docker" ??

**Comment by davidnemec** [comment]
Yes, should be enough.

**Comment by yoge67855** [comment]
i ran sudo systemctl enable --now docker.service docker and then i ran script with sudo (without sudo didnt work) SOLVED :D
