### ISSUE TITLE
ValueError: All strings must be XML compatible

### ISSUE THREAD

**Issue by timtoo** [davidnemec/bitwarden-to-keepass#5]
Don't know if this is worth bothering with. It might be helpful to at least trap these errors and print out the entry name that is causing the problem, to make it easier for a user to look into. Or a verbose mode that prints the data for each entry as it is read, so one can see where one is in case of a crash. I added a few prints to the code and tracked this down to note on a record that was simply: '\x10' (ascii character 16, or ^P). I have no idea how that got in my old crufty database, but it caused this:

```INFO:root:KeePass database does not exist, creating a new one.
INFO:root:Folders done (22).
INFO:root:Starting to process 1351 items.
Traceback (most recent call last):
  File "src/lxml/builder.py", line 175, in lxml.builder.ElementMaker.__init__.add_text
  File "src/lxml/etree.pyx", line 1161, in lxml.etree._Element.__getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/work/bitwarden-to-keepass/bitwarden-to-keepass.py", line 137, in <module>
    check_args(args) and bitwarden_to_keepass(args)
  File "/home/x/work/bitwarden-to-keepass/bitwarden-to-keepass.py", line 60, in bitwarden_to_keepass
    raise e
  File "/home/x/work/bitwarden-to-keepass/bitwarden-to-keepass.py", line 48, in bitwarden_to_keepass
    entry = kp.add_entry(
  File "/home/x/work/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/pykeepass/pykeepass.py", line 550, in add_entry
    entry = Entry(
  File "/home/x/work/bitwarden-to-keepass/.venv/lib/python3.9/site-packages/pykeepass/entry.py", line 57, in __init__
    self._element.append(E.String(E.Key('Notes'), E.Value(notes)))
  File "src/lxml/builder.py", line 228, in lxml.builder.ElementMaker.__call__
  File "src/lxml/builder.py", line 177, in lxml.builder.ElementMaker.__init__.add_text
  File "src/lxml/etree.pyx", line 1024, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 747, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 735, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1540, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

**Comment by davidnemec** [comment]
Yes, a little bit more user-friendly error with specific item that is causing some problems would be great. Maybe with some option to skip exporting these items. I will look into it.
