### ISSUE TITLE
TypeError NoneType(None)

### ISSUE THREAD

**Issue by JRussell** [davidnemec/bitwarden-to-keepass#6]
Tried running via docker compose. Any ideas?

I saw there was a closed issue with the same error but that looks like it was fixed.

Only thing I changed was adding an additional command to the docker compose to point it at my self hosted BW_RS.

```
2021-04-11 22:37:37 :: INFO :: KeePass database does not exist, creating a new one.
2021-04-11 22:37:41 :: INFO :: Folders done (26).
2021-04-11 22:37:45 :: INFO :: Starting to process 390 items.
Traceback (most recent call last):
  File "/bitwarden-to-keepass/bitwarden-to-keepass.py", line 147, in <module>
    check_args(args) and bitwarden_to_keepass(args)
  File "/bitwarden-to-keepass/bitwarden-to-keepass.py", line 78, in bitwarden_to_keepass
    entry.url = uri['uri']
  File "/usr/local/lib/python3.9/site-packages/pykeepass/entry.py", line 151, in url
    return self._set_string_field('URL', value)
  File "/usr/local/lib/python3.9/site-packages/pykeepass/entry.py", line 88, in _set_string_field
    self._element.append(E.String(E.Key(key), E.Value(value)))
  File "src/lxml/builder.py", line 226, in lxml.builder.ElementMaker.__call__
TypeError: bad argument type: NoneType(None)
```

**Comment by davidnemec** [comment]
My bad. Previous fix was catching errors only for basic fields (username, password, ...) but not for urls, notes and others.

Can you try switching to `catch-exceptions-update` branch and running docker-compose again (with --build param) to see if it helps? `git checkout origin/catch-exceptions-update`

**Comment by JRussell** [comment]
It worked! Thanks!
